global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "users-auth"
    static_configs:
      - targets: ["users-auth:3001"]
  # - job_name: "api-gateway"
  #   static_configs:
  #     - targets: ["api-gateway:3001"]
